# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/uav_simulator/Utils/quadrotor_msgs/msg/AuxCommand.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/uav_simulator/Utils/quadrotor_msgs/msg/Corrections.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/uav_simulator/Utils/quadrotor_msgs/msg/Gains.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/uav_simulator/Utils/quadrotor_msgs/msg/OutputData.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/uav_simulator/Utils/quadrotor_msgs/msg/PositionCommand.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/uav_simulator/Utils/quadrotor_msgs/msg/PPROutputData.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/uav_simulator/Utils/quadrotor_msgs/msg/Serial.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/uav_simulator/Utils/quadrotor_msgs/msg/SO3Command.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/uav_simulator/Utils/quadrotor_msgs/msg/StatusData.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/uav_simulator/Utils/quadrotor_msgs/msg/TRPYCommand.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/uav_simulator/Utils/quadrotor_msgs/msg/Odometry.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/uav_simulator/Utils/quadrotor_msgs/msg/PolynomialTrajectory.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/uav_simulator/Utils/quadrotor_msgs/msg/LQRTrajectory.msg"
services_str = ""
pkg_name = "quadrotor_msgs"
dependencies_str = "geometry_msgs;nav_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "quadrotor_msgs;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/uav_simulator/Utils/quadrotor_msgs/msg;geometry_msgs;/opt/ros/noetic/share/geometry_msgs/cmake/../msg;nav_msgs;/opt/ros/noetic/share/nav_msgs/cmake/../msg;std_msgs;/opt/ros/noetic/share/std_msgs/cmake/../msg;actionlib_msgs;/opt/ros/noetic/share/actionlib_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python3"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/noetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
