# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/unitree_guide/unitree_ros_to_real/unitree_legged_msgs/msg/MotorCmd.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/unitree_guide/unitree_ros_to_real/unitree_legged_msgs/msg/MotorState.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/unitree_guide/unitree_ros_to_real/unitree_legged_msgs/msg/BmsCmd.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/unitree_guide/unitree_ros_to_real/unitree_legged_msgs/msg/BmsState.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/unitree_guide/unitree_ros_to_real/unitree_legged_msgs/msg/Cartesian.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/unitree_guide/unitree_ros_to_real/unitree_legged_msgs/msg/IMU.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/unitree_guide/unitree_ros_to_real/unitree_legged_msgs/msg/LED.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/unitree_guide/unitree_ros_to_real/unitree_legged_msgs/msg/LowCmd.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/unitree_guide/unitree_ros_to_real/unitree_legged_msgs/msg/LowState.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/unitree_guide/unitree_ros_to_real/unitree_legged_msgs/msg/HighCmd.msg;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/unitree_guide/unitree_ros_to_real/unitree_legged_msgs/msg/HighState.msg"
services_str = ""
pkg_name = "unitree_legged_msgs"
dependencies_str = "std_msgs;geometry_msgs;sensor_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "unitree_legged_msgs;/root/autodl-tmp/code/restore/0803b/overall_l0829/SimEnv-master/src/unitree_guide/unitree_ros_to_real/unitree_legged_msgs/msg;std_msgs;/opt/ros/noetic/share/std_msgs/cmake/../msg;geometry_msgs;/opt/ros/noetic/share/geometry_msgs/cmake/../msg;sensor_msgs;/opt/ros/noetic/share/sensor_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python3"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/noetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
